<?php
/**
 * @var array $availableCurrencies
 * @var array $js
 * @var array $css
 */

$title = 'Поиск маршрута';
$this->layout('layout', compact('title', 'js', 'css'));
?>
<div class="card">
    <div class="card-header">
        <?= $title ?>
    </div>
    <div class="card-body">
        <form id="train-route-finder">
            <fieldset>
                <div class="form-group">
                    <label for="train-number">Номер поезда</label>
                    <input type="text" class="form-control" id="train-number" name="trainNumber" placeholder="016А">
                    <div class="invalid-feedback">Неверное значение</div>
                </div>

                <div class="form-group">
                    <label for="departure-date">Дата отправления</label>
                    <input type="date" class="form-control" id="departure-date" name="departureDate">
                    <div class="invalid-feedback">Неверное значение</div>
                </div>

                <div class="form-group">
                    <label for="departure-station">Станция отправления</label>
                    <input type="text" class="form-control" id="departure-station" name="departureStation" placeholder="Санкт-Петербург">
                    <div class="invalid-feedback">Неверное значение</div>
                </div>

                <div class="form-group">
                    <label for="arrival-station">Станция прибытия</label>
                    <input type="text" class="form-control" id="arrival-station" name="arrivalStation" placeholder="Москва">
                    <div class="invalid-feedback">Неверное значение</div>
                </div>

                <button type="submit" class="btn btn-primary mt-3"><span class="find-icon">🔎</span> Найти маршрут</button>
            </fieldset>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="results-modal" tabindex="-1" role="dialog" aria-labelledby="results-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="results-modal-title">Результат</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>