<?php
/**
 * @var string $title
 * @var array|null $css
 * @var array|null $js
 */

$css = array_merge([
    '/node_modules/bootstrap/dist/css/bootstrap.min.css',
    '/assets/css/common.css',
], $css ?? []);

$js = array_merge([
    '/node_modules/jquery/dist/jquery.min.js',
    '/node_modules/bootstrap/dist/js/bootstrap.min.js',
], $js ?? []);
?>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <title><?= $this->e($title) ?> | PHP Train Route Test Task</title>

    <?php foreach ($css ?? [] as $path): ?>
        <link rel="stylesheet" href="<?= $path ?>">
    <?php endforeach; ?>
</head>
<body>
<div class="container min-vh-100">
    <div class="row h-100 justify-content-center align-items-center">
        <?= $this->section('content') ?>
    </div>
</div>

<?php foreach ($js ?? [] as $path): ?>
    <script type="text/javascript" src="<?= $path ?>"></script>
<?php endforeach; ?>
</body>
</html>