<?php
/**
 * @var $title string
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <link rel="stylesheet" href="/assets/node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/common.css">
    <?php if (isset($css)): ?>
        <?php foreach ($css as $path): ?>
            <link rel="stylesheet" href="<?= $path ?>">
        <?php endforeach; ?>
    <?php endif; ?>

    <title><?= $this->e($title) ?> | PHP Train Route Test Task</title>
</head>
<body>
<div class="container min-vh-100">
    <div class="row h-100 justify-content-center align-items-center">
        <?= $this->section('content') ?>
    </div>
</div>

<script type="text/javascript" src="/assets/node_modules/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="/assets/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<?php if (isset($js)): ?>
    <?php foreach ($js as $path): ?>
        <script type="text/javascript" src="<?= $path ?>"></script>
    <?php endforeach; ?>
<?php endif; ?>
</body>
</html>